name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      BACKEND_IMAGE: ghcr.io/lavanururohithroy/ai-code-plagiarism-detector/backend:latest
      FRONTEND_IMAGE: ghcr.io/lavanururohithroy/ai-code-plagiarism-detector/frontend:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ---------- BACKEND ----------

      - name: Build backend
        run: |
          docker build \
          -f docker/backend.Dockerfile \
          -t $BACKEND_IMAGE \
          .

      - name: Push backend
        run: |
          docker push $BACKEND_IMAGE

      # ---------- FRONTEND ----------

      - name: Build frontend
        run: |
          docker build \
          -f docker/frontend.Dockerfile \
          -t $FRONTEND_IMAGE \
          .

      - name: Push frontend
        run: |
          docker push $FRONTEND_IMAGE